language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

php:
  - 7.2
  - 7.3

env:
    global:
        - TEST_COMMAND="vendor/bin/phpunit"

matrix:
    fast_finish: true

    include:
        - php: 7.2
          env: SYMFONY_VERSION=^3.0
        - php: 7.3
          env: SYMFONY_VERSION=^3.0
        - php: 7.2
          env: SYMFONY_VERSION=^4.0
        - php: 7.3
          env: SYMFONY_VERSION=^4.0

before_install:
    - travis_retry composer self-update

install:
    - composer require symfony/symfony:${SYMFONY_VERSION} --no-update
    - composer update ${COMPOSER_FLAGS} --prefer-source --no-interaction

script:
    - $TEST_COMMAND
