services:
    NS\ColorAdminBundle\Menu\MenuBuilder:
        arguments: ["@knp_menu.factory"]
        tags:
            - { name: knp_menu.menu_builder, method: createSidebarMenu, alias: sidebar } # The alias is what is used to retrieve the menu
            - { name: knp_menu.menu_builder, method: createSidebarMenu, alias: breadcrumbs }

    NS\ColorAdminBundle\Twig\TemplateExtension:
        arguments: [ "%color_admin.templates%" ]
        tags:
            - { name: twig.extension }

    NS\ColorAdminBundle\Form\Extension\MaskExtension:
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\TextType }

    NS\ColorAdminBundle\Form\Extension\IconExtension:
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\TextType }

    NS\ColorAdminBundle\Form\Extension\OrientationExtension:
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\FormType }

    NS\ColorAdminBundle\Form\Extension\DetailsExtension:
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\FormType }

    NS\ColorAdminBundle\Form\Extension\PasswordExtension:
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\PasswordType }
